stages:
  - test

variables:
  PYTHON_VERSION: "3.8"

before_script:
  - python3 -m venv venv
  - source venv/bin/activate

test:
  stage: test
  script:
    - python script.py &  # Run script.py in the background
    - sleep 5  # Give script.py some time to start (adjust as needed)
    - echo "he a = 5" | python basic.py  # Replace "User Input" with your actual input
    - pkill -f "python script.py"  # Terminate the background process
