stages:
  - test

variables:
  PYTHON_VERSION: "3.8"

before_script:
  - apt-get update -qy  # Update package index
  - apt-get install -y python3-venv  # Install python3-venv package
  - python3 -m venv venv
  - source venv/bin/activate

test:
  stage: test
  script:
    - ps aux | grep "python3.8 script.py"
    - python3.8 script.py &
    - sleep 5
    - echo "5" | python3.8 basic.py
    - pkill -f "python3.8 script.py"
    - ps aux | grep "python3.8 script.py"

  after_script:
  - deactivate
  - rm -rf venv

